parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  project: './tsconfig.development.json'
env:
  browser: true
  jest: true
plugins:
  - '@typescript-eslint'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'airbnb-typescript/base'
  - 'prettier'
  - 'prettier/@typescript-eslint'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  import/prefer-default-export: off
settings:
  'import/resolver':
    node:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
