sudo: false
language: node_js
cache:
  yarn: true
node_js:
  - 10
install:
  - yarn
  - yarn add preact --peer
after_success:
  - yarn add coveralls;
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
